/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#83cfff",
        "surface-tint": "#ffb4ab",
        "surface-container-high": "#2a2a2e",
        "on-secondary-container": "#b6b4ba",
        "background": "#000000",
        "on-error": "#690005",
        "primary-fixed-dim": "#ffb4ab",
        "surface-variant": "#1A1A1E",
        "surface-dim": "#0E0E11",
        "secondary": "#c8c5cb",
        "on-tertiary-fixed-variant": "#004c6c",
        "surface-container-low": "#0A0A0C",
        "surface-container-lowest": "#000000",
        "on-background": "#e4e1e7",
        "secondary-container": "#47464b",
        "inverse-surface": "#e4e1e7",
        "on-primary-fixed-variant": "#93000d",
        "surface-bright": "#39393d",
        "secondary-fixed-dim": "#c8c5cb",
        "on-surface-variant": "#e5bdb9",
        "on-primary": "#690006",
        "tertiary-container": "#0077a6",
        "on-secondary-fixed": "#1b1b1f",
        "primary-fixed": "#ffdad6",
        "error": "#ffb4ab",
        "surface": "#000000",
        "on-tertiary-container": "#ebf5ff",
        "on-primary-container": "#fff1ef",
        "primary": "#d62828",
        "on-secondary": "#303034",
        "surface-container": "#131317",
        "on-surface": "#e4e1e7",
        "tertiary-fixed-dim": "#83cfff",
        "inverse-primary": "#bd1119",
        "surface-container-highest": "#343438",
        "on-tertiary-fixed": "#001e2e",
        "primary-container": "#d62828",
        "inverse-on-surface": "#303034",
        "secondary-fixed": "#e4e1e7",
        "on-tertiary": "#00344c",
        "on-primary-fixed": "#410002",
        "outline": "#ac8884",
        "tertiary-fixed": "#c7e7ff",
        "on-secondary-fixed-variant": "#47464b",
        "outline-variant": "#5c403d",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a"
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "base": "4px",
        "xl": "64px",
        "margin-desktop": "48px",
        "sm": "16px",
        "xs": "8px",
        "md": "24px",
        "gutter": "24px",
        "lg": "40px"
      },
      fontFamily: {
        "headline-xl": ["Poppins"],
        "label-caps": ["JetBrains Mono"],
        "data-mono": ["JetBrains Mono"],
        "headline-lg": ["Poppins"],
        "body-md": ["Poppins"],
        "body-lg": ["Poppins"],
        "headline-lg-mobile": ["Poppins"],
        "headline-md": ["Poppins"]
      },
      fontSize: {
        "headline-xl": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "800" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "data-mono": ["14px", { "lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "400" }],
        "headline-lg": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "900" }],
        "body-md": ["16px", { "lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}